# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with packages for j5ltexx configurations
Name: jolla-configuration-j5ltexx
Requires:
- pattern:jolla-hw-adaptation-j5ltexx
- pattern:jolla-sailfish-applications
- pattern:jolla-ui-wayland
# Early stages of porting benefit from these:
- pattern:sailfish-porter-tools

Summary: Jolla Configuration j5ltexx

